### ISSUE TITLE
Disc doesn't create. 

### ISSUE THREAD

**Issue by TDW333** [mrmrmystery/Mixer#3]
YouTube doesn't work. SoundCloud have problems. Please check if it's not my server bug. THX

**Comment by phAtl13** [comment]
Same here with all my servers, doesn't create discs and jsut displays "playback stopped" on currently made discs

**Comment by mrmrmystery** [comment]
I updated lavaplayer. It should work now https://modrinth.com/plugin/mixer/version/1.0.3
