### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by phAtl13** [mrmrmystery/Mixer#4]
Hi there, just wondering if there's any issues with the compatibility of mixer/ lava player with the update for svc that released on 29th of March? Players on my server network are pestering me like crazy haha, and I've tried explaining it's not me that makes it, was like, give the dev time to work his magic lol

**Comment by mrmrmystery** [comment]
Seems like youtube changed some stuff the last days and youtube links don't play anymore. I need to wait until lavaplayer fixes the issue.

**Comment by phAtl13** [comment]
no problem, thanks for taking the time to reply :) and still, one of the best plugins ever created :)
